// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.7.7
//   protoc               v6.33.0
// source: location.proto

/* eslint-disable */
import { GrpcMethod, GrpcStreamMethod } from "@nestjs/microservices";
import { Observable } from "rxjs";

export const protobufPackage = "location";

export interface CoordinatesRequest {
  location: string;
}

export interface CoordinatesResponse {
  lat: number;
  lng: number;
}

export interface DistanceRequest {
  origin: string;
  destination: string;
}

export interface DistanceResponse {
  distanceText: string;
  distanceValue: number;
  durationText: string;
  durationValue: number;
}

export const LOCATION_PACKAGE_NAME = "location";

export interface LocationServiceClient {
  getCoordinates(request: CoordinatesRequest): Observable<CoordinatesResponse>;

  getDistance(request: DistanceRequest): Observable<DistanceResponse>;
}

export interface LocationServiceController {
  getCoordinates(
    request: CoordinatesRequest,
  ): Promise<CoordinatesResponse> | Observable<CoordinatesResponse> | CoordinatesResponse;

  getDistance(request: DistanceRequest): Promise<DistanceResponse> | Observable<DistanceResponse> | DistanceResponse;
}

export function LocationServiceControllerMethods() {
  return function (constructor: Function) {
    const grpcMethods: string[] = ["getCoordinates", "getDistance"];
    for (const method of grpcMethods) {
      const descriptor: any = Reflect.getOwnPropertyDescriptor(constructor.prototype, method);
      GrpcMethod("LocationService", method)(constructor.prototype[method], method, descriptor);
    }
    const grpcStreamMethods: string[] = [];
    for (const method of grpcStreamMethods) {
      const descriptor: any = Reflect.getOwnPropertyDescriptor(constructor.prototype, method);
      GrpcStreamMethod("LocationService", method)(constructor.prototype[method], method, descriptor);
    }
  };
}

export const LOCATION_SERVICE_NAME = "LocationService";
