// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.7.7
//   protoc               v6.33.0
// source: rating.proto

/* eslint-disable */
import { GrpcMethod, GrpcStreamMethod } from "@nestjs/microservices";
import { Observable } from "rxjs";

export const protobufPackage = "rating";

export interface UpsertRatingRequest {
  userId: string;
  shrineId: string;
  rating: number;
  review?: string | undefined;
  isAnonymous?: boolean | undefined;
}

export interface RatingResponse {
  id: string;
  userId: string;
  shrineId: string;
  rating: number;
  review?: string | undefined;
  isAnonymous: boolean;
  createdAt: string;
  updatedAt: string;
}

export interface GetShrineRatingsRequest {
  shrineId: string;
  sortBy?: string | undefined;
  page?: number | undefined;
  limit?: number | undefined;
}

export interface RatingItem {
  id: string;
  userId: string;
  userName?: string | undefined;
  userAvatar?: string | undefined;
  rating: number;
  review?: string | undefined;
  isAnonymous: boolean;
  createdAt: string;
}

export interface ShrineRatingsResponse {
  ratings: RatingItem[];
  averageRating: number;
  totalReviews: number;
  total: number;
  page: number;
  totalPages: number;
}

export interface GetUserRatingsRequest {
  userId: string;
  page?: number | undefined;
  limit?: number | undefined;
}

export interface UserRatingItem {
  id: string;
  shrineId: string;
  shrineName: string;
  shrineProvince: string;
  rating: number;
  review?: string | undefined;
  createdAt: string;
}

export interface UserRatingsResponse {
  ratings: UserRatingItem[];
  total: number;
  page: number;
  totalPages: number;
}

export interface GetShrineStatsRequest {
  shrineId: string;
}

export interface RatingDistribution {
  five: number;
  four: number;
  three: number;
  two: number;
  one: number;
}

export interface ShrineStatsResponse {
  shrineId: string;
  averageRating: number;
  totalReviews: number;
  ratingDistribution: RatingDistribution | undefined;
}

export interface MultipleShrineStatsRequest {
  shrineIds: string[];
}

export interface ShrineStatItem {
  shrineId: string;
  averageRating: number;
  totalReviews: number;
}

export interface MultipleShrineStatsResponse {
  stats: ShrineStatItem[];
}

export interface DeleteRatingRequest {
  id: string;
  userId: string;
}

export interface DeleteRatingResponse {
  success: boolean;
  message: string;
}

export const RATING_PACKAGE_NAME = "rating";

export interface RatingServiceClient {
  upsertRating(request: UpsertRatingRequest): Observable<RatingResponse>;

  getShrineRatings(request: GetShrineRatingsRequest): Observable<ShrineRatingsResponse>;

  getUserRatings(request: GetUserRatingsRequest): Observable<UserRatingsResponse>;

  getShrineStats(request: GetShrineStatsRequest): Observable<ShrineStatsResponse>;

  getMultipleShrineStats(request: MultipleShrineStatsRequest): Observable<MultipleShrineStatsResponse>;

  deleteRating(request: DeleteRatingRequest): Observable<DeleteRatingResponse>;
}

export interface RatingServiceController {
  upsertRating(request: UpsertRatingRequest): Promise<RatingResponse> | Observable<RatingResponse> | RatingResponse;

  getShrineRatings(
    request: GetShrineRatingsRequest,
  ): Promise<ShrineRatingsResponse> | Observable<ShrineRatingsResponse> | ShrineRatingsResponse;

  getUserRatings(
    request: GetUserRatingsRequest,
  ): Promise<UserRatingsResponse> | Observable<UserRatingsResponse> | UserRatingsResponse;

  getShrineStats(
    request: GetShrineStatsRequest,
  ): Promise<ShrineStatsResponse> | Observable<ShrineStatsResponse> | ShrineStatsResponse;

  getMultipleShrineStats(
    request: MultipleShrineStatsRequest,
  ): Promise<MultipleShrineStatsResponse> | Observable<MultipleShrineStatsResponse> | MultipleShrineStatsResponse;

  deleteRating(
    request: DeleteRatingRequest,
  ): Promise<DeleteRatingResponse> | Observable<DeleteRatingResponse> | DeleteRatingResponse;
}

export function RatingServiceControllerMethods() {
  return function (constructor: Function) {
    const grpcMethods: string[] = [
      "upsertRating",
      "getShrineRatings",
      "getUserRatings",
      "getShrineStats",
      "getMultipleShrineStats",
      "deleteRating",
    ];
    for (const method of grpcMethods) {
      const descriptor: any = Reflect.getOwnPropertyDescriptor(constructor.prototype, method);
      GrpcMethod("RatingService", method)(constructor.prototype[method], method, descriptor);
    }
    const grpcStreamMethods: string[] = [];
    for (const method of grpcStreamMethods) {
      const descriptor: any = Reflect.getOwnPropertyDescriptor(constructor.prototype, method);
      GrpcStreamMethod("RatingService", method)(constructor.prototype[method], method, descriptor);
    }
  };
}

export const RATING_SERVICE_NAME = "RatingService";
