// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.7.7
//   protoc               v6.33.0
// source: shrine-discovery.proto

/* eslint-disable */
import { GrpcMethod, GrpcStreamMethod } from "@nestjs/microservices";
import { Observable } from "rxjs";

export const protobufPackage = "shrine_discovery";

/** Request messages */
export interface RecommendShrineRequest {
  userId: string;
  wishText: string;
  /** love, career, wealth, health, etc. */
  wishCategory: string;
  latitude?: number | undefined;
  longitude?:
    | number
    | undefined;
  /** default 10km */
  maxDistanceKm?: number | undefined;
}

export interface GetNearbyShrineRequest {
  location: string;
  /** default 10km */
  radiusKm?:
    | number
    | undefined;
  /** popularity, rating, distance */
  sortBy?: string | undefined;
}

export interface SearchByCategoryRequest {
  /** love, career, wealth, health */
  category: string;
  latitude?: number | undefined;
  longitude?: number | undefined;
}

/** Response messages */
export interface ShrineRecommendation {
  shrineId: string;
  shrineName: string;
  description: string;
  location: string;
  rating: number;
  distanceKm: number;
  durationText: string;
  category: string;
  /** 0-100 how well it matches the wish */
  matchScore: number;
  /** why this shrine was recommended */
  reason: string;
}

export interface RecommendShrineResponse {
  recommendations: ShrineRecommendation[];
  /** AI-categorized wish type */
  categorizedWish: string;
}

export interface ShrinesListResponse {
  shrines: ShrineRecommendation[];
}

/** New search and recommend messages */
export interface SearchShrinesRequest {
  query?: string | undefined;
  category: string[];
  shrineType?: string | undefined;
  latitude?: number | undefined;
  longitude?: number | undefined;
  maxDistance?: number | undefined;
  minRating?: number | undefined;
  sortBy?: string | undefined;
  sortOrder?: string | undefined;
  page?: number | undefined;
  limit?: number | undefined;
}

export interface ShrineItem {
  id: string;
  name: string;
  description: string;
  category: string[];
  shrineType: string;
  latitude: number;
  longitude: number;
  distance?: number | undefined;
  averageRating: number;
  totalReviews: number;
  totalWishes: number;
  photoUrl?: string | undefined;
}

export interface SearchShrinesResponse {
  shrines: ShrineItem[];
  total: number;
  page: number;
  totalPages: number;
}

export interface RecommendShrinesRequest {
  userId: string;
  category: string;
  latitude?: number | undefined;
  longitude?: number | undefined;
  maxDistance?: number | undefined;
  limit?: number | undefined;
}

export interface RecommendationItem {
  id: string;
  name: string;
  description: string;
  category: string[];
  matchScore: number;
  averageRating: number;
  totalReviews: number;
  totalWishes: number;
  distance?: number | undefined;
  reason: string;
}

export interface RecommendShrinesResponse {
  recommendations: RecommendationItem[];
}

export interface GetShrineAggregatedStatsRequest {
  shrineId: string;
}

export interface CategoryCount {
  category: string;
  count: number;
}

export interface RatingDistribution {
  five: number;
  four: number;
  three: number;
  two: number;
  one: number;
}

export interface ShrineAggregatedStatsResponse {
  id: string;
  averageRating: number;
  totalReviews: number;
  ratingDistribution: RatingDistribution | undefined;
  totalWishes: number;
  recentWishesCount: number;
  popularCategories: CategoryCount[];
}

export interface Empty {
}

export const SHRINE_DISCOVERY_PACKAGE_NAME = "shrine_discovery";

export interface ShrineDiscoveryServiceClient {
  recommendShrine(request: RecommendShrineRequest): Observable<RecommendShrineResponse>;

  getNearbyShrine(request: GetNearbyShrineRequest): Observable<ShrinesListResponse>;

  searchShrinesByCategory(request: SearchByCategoryRequest): Observable<ShrinesListResponse>;

  searchShrines(request: SearchShrinesRequest): Observable<SearchShrinesResponse>;

  recommendShrines(request: RecommendShrinesRequest): Observable<RecommendShrinesResponse>;

  getShrineAggregatedStats(request: GetShrineAggregatedStatsRequest): Observable<ShrineAggregatedStatsResponse>;
}

export interface ShrineDiscoveryServiceController {
  recommendShrine(
    request: RecommendShrineRequest,
  ): Promise<RecommendShrineResponse> | Observable<RecommendShrineResponse> | RecommendShrineResponse;

  getNearbyShrine(
    request: GetNearbyShrineRequest,
  ): Promise<ShrinesListResponse> | Observable<ShrinesListResponse> | ShrinesListResponse;

  searchShrinesByCategory(
    request: SearchByCategoryRequest,
  ): Promise<ShrinesListResponse> | Observable<ShrinesListResponse> | ShrinesListResponse;

  searchShrines(
    request: SearchShrinesRequest,
  ): Promise<SearchShrinesResponse> | Observable<SearchShrinesResponse> | SearchShrinesResponse;

  recommendShrines(
    request: RecommendShrinesRequest,
  ): Promise<RecommendShrinesResponse> | Observable<RecommendShrinesResponse> | RecommendShrinesResponse;

  getShrineAggregatedStats(
    request: GetShrineAggregatedStatsRequest,
  ): Promise<ShrineAggregatedStatsResponse> | Observable<ShrineAggregatedStatsResponse> | ShrineAggregatedStatsResponse;
}

export function ShrineDiscoveryServiceControllerMethods() {
  return function (constructor: Function) {
    const grpcMethods: string[] = [
      "recommendShrine",
      "getNearbyShrine",
      "searchShrinesByCategory",
      "searchShrines",
      "recommendShrines",
      "getShrineAggregatedStats",
    ];
    for (const method of grpcMethods) {
      const descriptor: any = Reflect.getOwnPropertyDescriptor(constructor.prototype, method);
      GrpcMethod("ShrineDiscoveryService", method)(constructor.prototype[method], method, descriptor);
    }
    const grpcStreamMethods: string[] = [];
    for (const method of grpcStreamMethods) {
      const descriptor: any = Reflect.getOwnPropertyDescriptor(constructor.prototype, method);
      GrpcStreamMethod("ShrineDiscoveryService", method)(constructor.prototype[method], method, descriptor);
    }
  };
}

export const SHRINE_DISCOVERY_SERVICE_NAME = "ShrineDiscoveryService";
