// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.7.7
//   protoc               v6.33.0
// source: shrine.proto

/* eslint-disable */
import { GrpcMethod, GrpcStreamMethod } from "@nestjs/microservices";
import { Observable } from "rxjs";

export const protobufPackage = "shrine";

export interface CreateShrineRequest {
  name: string;
  description: string;
  location: string;
  imageUrl?: string | undefined;
  category?: string | undefined;
}

export interface FindShrineByIdRequest {
  id: string;
}

export interface UpdateShrineByIdRequest {
  id: string;
  name?: string | undefined;
  description?: string | undefined;
  location?: string | undefined;
  imageUrl?: string | undefined;
  category?: string | undefined;
}

export interface DeleteShrineByIdRequest {
  id: string;
}

export interface ShrineResponse {
  id: string;
  name: string;
  description: string;
  lat: number;
  lng: number;
  location: string;
  createdAt: string;
  updatedAt: string;
  imageUrl?: string | undefined;
  category?: string | undefined;
}

export interface ShrinesResponse {
  shrines: ShrineResponse[];
}

export interface Empty {
}

export const SHRINE_PACKAGE_NAME = "shrine";

export interface ShrineServiceClient {
  createShrine(request: CreateShrineRequest): Observable<ShrineResponse>;

  findShrineById(request: FindShrineByIdRequest): Observable<ShrineResponse>;

  findAllShrines(request: Empty): Observable<ShrinesResponse>;

  updateShrineById(request: UpdateShrineByIdRequest): Observable<ShrineResponse>;

  deleteShrineById(request: FindShrineByIdRequest): Observable<ShrineResponse>;
}

export interface ShrineServiceController {
  createShrine(request: CreateShrineRequest): Promise<ShrineResponse> | Observable<ShrineResponse> | ShrineResponse;

  findShrineById(request: FindShrineByIdRequest): Promise<ShrineResponse> | Observable<ShrineResponse> | ShrineResponse;

  findAllShrines(request: Empty): Promise<ShrinesResponse> | Observable<ShrinesResponse> | ShrinesResponse;

  updateShrineById(
    request: UpdateShrineByIdRequest,
  ): Promise<ShrineResponse> | Observable<ShrineResponse> | ShrineResponse;

  deleteShrineById(
    request: FindShrineByIdRequest,
  ): Promise<ShrineResponse> | Observable<ShrineResponse> | ShrineResponse;
}

export function ShrineServiceControllerMethods() {
  return function (constructor: Function) {
    const grpcMethods: string[] = [
      "createShrine",
      "findShrineById",
      "findAllShrines",
      "updateShrineById",
      "deleteShrineById",
    ];
    for (const method of grpcMethods) {
      const descriptor: any = Reflect.getOwnPropertyDescriptor(constructor.prototype, method);
      GrpcMethod("ShrineService", method)(constructor.prototype[method], method, descriptor);
    }
    const grpcStreamMethods: string[] = [];
    for (const method of grpcStreamMethods) {
      const descriptor: any = Reflect.getOwnPropertyDescriptor(constructor.prototype, method);
      GrpcStreamMethod("ShrineService", method)(constructor.prototype[method], method, descriptor);
    }
  };
}

export const SHRINE_SERVICE_NAME = "ShrineService";
