// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.7.7
//   protoc               v6.33.0
// source: technique.proto

/* eslint-disable */
import { GrpcMethod, GrpcStreamMethod } from "@nestjs/microservices";
import { Observable } from "rxjs";

export const protobufPackage = "technique";

/** Technique message */
export interface Technique {
  /** tech id */
  id: string;
  /** shrine id */
  shrineId: string;
  /** user id */
  userId: string;
  /** title of the technique */
  title: string;
  /** description of the technique */
  description: string;
  /** list of ingredients */
  ingredients: string[];
}

/** Request messages */
export interface CreateTechniqueRequest {
  shrineId: string;
  userId: string;
  title: string;
  description: string;
  ingredients: string[];
}

export interface UpdateTechniqueRequest {
  id: string;
  title: string;
  description: string;
  ingredients: string[];
}

export interface GetTechniqueRequest {
  id: string;
}

export interface DeleteTechniqueRequest {
  id: string;
}

/** Response messages */
export interface TechniqueResponse {
  technique: Technique | undefined;
}

export interface TechniquesResponse {
  techniques: Technique[];
}

export interface Empty {
}

export const TECHNIQUE_PACKAGE_NAME = "technique";

export interface TechniqueServiceClient {
  createTechnique(request: CreateTechniqueRequest): Observable<TechniqueResponse>;

  updateTechnique(request: UpdateTechniqueRequest): Observable<TechniqueResponse>;

  deleteTechnique(request: DeleteTechniqueRequest): Observable<TechniqueResponse>;

  findTechniqueById(request: GetTechniqueRequest): Observable<TechniqueResponse>;

  listTechniques(request: Empty): Observable<TechniquesResponse>;
}

export interface TechniqueServiceController {
  createTechnique(
    request: CreateTechniqueRequest,
  ): Promise<TechniqueResponse> | Observable<TechniqueResponse> | TechniqueResponse;

  updateTechnique(
    request: UpdateTechniqueRequest,
  ): Promise<TechniqueResponse> | Observable<TechniqueResponse> | TechniqueResponse;

  deleteTechnique(
    request: DeleteTechniqueRequest,
  ): Promise<TechniqueResponse> | Observable<TechniqueResponse> | TechniqueResponse;

  findTechniqueById(
    request: GetTechniqueRequest,
  ): Promise<TechniqueResponse> | Observable<TechniqueResponse> | TechniqueResponse;

  listTechniques(request: Empty): Promise<TechniquesResponse> | Observable<TechniquesResponse> | TechniquesResponse;
}

export function TechniqueServiceControllerMethods() {
  return function (constructor: Function) {
    const grpcMethods: string[] = [
      "createTechnique",
      "updateTechnique",
      "deleteTechnique",
      "findTechniqueById",
      "listTechniques",
    ];
    for (const method of grpcMethods) {
      const descriptor: any = Reflect.getOwnPropertyDescriptor(constructor.prototype, method);
      GrpcMethod("TechniqueService", method)(constructor.prototype[method], method, descriptor);
    }
    const grpcStreamMethods: string[] = [];
    for (const method of grpcStreamMethods) {
      const descriptor: any = Reflect.getOwnPropertyDescriptor(constructor.prototype, method);
      GrpcStreamMethod("TechniqueService", method)(constructor.prototype[method], method, descriptor);
    }
  };
}

export const TECHNIQUE_SERVICE_NAME = "TechniqueService";
