// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.7.7
//   protoc               v6.33.0
// source: user.proto

/* eslint-disable */
import { GrpcMethod, GrpcStreamMethod } from "@nestjs/microservices";
import { Observable } from "rxjs";

export const protobufPackage = "user";

export interface CreateUserRequest {
  email: string;
  password: string;
  role: string;
}

export interface FindUserByIdRequest {
  id: string;
}

export interface UpdateUserByIdRequest {
  id: string;
  email?: string | undefined;
  password?: string | undefined;
  role?: string | undefined;
}

export interface DeleteUserByIdRequest {
  id: string;
}

export interface LoginRequest {
  email: string;
  password: string;
}

export interface LoginResponse {
  accessToken: string;
  user: UserResponse | undefined;
}

export interface UserResponse {
  id: string;
  email: string;
  role: string;
  createdAt: string;
  updatedAt: string;
}

export interface UsersResponse {
  users: UserResponse[];
}

export interface Empty {
}

export const USER_PACKAGE_NAME = "user";

export interface UserServiceClient {
  healthCheck(request: Empty): Observable<Empty>;

  createUser(request: CreateUserRequest): Observable<UserResponse>;

  login(request: LoginRequest): Observable<LoginResponse>;

  findUserById(request: FindUserByIdRequest): Observable<UserResponse>;

  findAllUsers(request: Empty): Observable<UsersResponse>;

  updateUserById(request: UpdateUserByIdRequest): Observable<UserResponse>;

  deleteUserById(request: FindUserByIdRequest): Observable<UserResponse>;
}

export interface UserServiceController {
  healthCheck(request: Empty): Promise<Empty> | Observable<Empty> | Empty;

  createUser(request: CreateUserRequest): Promise<UserResponse> | Observable<UserResponse> | UserResponse;

  login(request: LoginRequest): Promise<LoginResponse> | Observable<LoginResponse> | LoginResponse;

  findUserById(request: FindUserByIdRequest): Promise<UserResponse> | Observable<UserResponse> | UserResponse;

  findAllUsers(request: Empty): Promise<UsersResponse> | Observable<UsersResponse> | UsersResponse;

  updateUserById(request: UpdateUserByIdRequest): Promise<UserResponse> | Observable<UserResponse> | UserResponse;

  deleteUserById(request: FindUserByIdRequest): Promise<UserResponse> | Observable<UserResponse> | UserResponse;
}

export function UserServiceControllerMethods() {
  return function (constructor: Function) {
    const grpcMethods: string[] = [
      "healthCheck",
      "createUser",
      "login",
      "findUserById",
      "findAllUsers",
      "updateUserById",
      "deleteUserById",
    ];
    for (const method of grpcMethods) {
      const descriptor: any = Reflect.getOwnPropertyDescriptor(constructor.prototype, method);
      GrpcMethod("UserService", method)(constructor.prototype[method], method, descriptor);
    }
    const grpcStreamMethods: string[] = [];
    for (const method of grpcStreamMethods) {
      const descriptor: any = Reflect.getOwnPropertyDescriptor(constructor.prototype, method);
      GrpcStreamMethod("UserService", method)(constructor.prototype[method], method, descriptor);
    }
  };
}

export const USER_SERVICE_NAME = "UserService";
