// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.7.7
//   protoc               v6.33.0
// source: wishing.proto

/* eslint-disable */
import { GrpcMethod, GrpcStreamMethod } from "@nestjs/microservices";
import { Observable } from "rxjs";

export const protobufPackage = "wishing";

export interface CreateWishRequest {
  wisherId: string;
  shrineId: string;
  wisherName?: string | undefined;
  description: string;
  public?: boolean | undefined;
}

export interface FindWishByIdRequest {
  id: string;
}

export interface FindAllWishesRequest {
  shrineId?: string | undefined;
  wisherId?: string | undefined;
}

export interface UpdateWishByIdRequest {
  id: string;
  wisherId?: string | undefined;
  shrineId?: string | undefined;
  wisherName?: string | undefined;
  description?: string | undefined;
  public?: boolean | undefined;
}

export interface WishResponse {
  id: string;
  wisherId: string;
  shrineId: string;
  wisherName: string;
  description: string;
  public: boolean;
  createdAt: string;
  updatedAt: string;
}

export interface WishesResponse {
  wishes: WishResponse[];
}

export interface GetShrineWishCountRequest {
  shrineId: string;
}

export interface CategoryCount {
  category: string;
  count: number;
}

export interface ShrineWishCountResponse {
  shrineId: string;
  totalWishes: number;
  recentWishesCount: number;
  popularCategories: CategoryCount[];
}

export const WISHING_PACKAGE_NAME = "wishing";

export interface WishingServiceClient {
  createWish(request: CreateWishRequest): Observable<WishResponse>;

  findWishById(request: FindWishByIdRequest): Observable<WishResponse>;

  findAllWishes(request: FindAllWishesRequest): Observable<WishesResponse>;

  updateWishById(request: UpdateWishByIdRequest): Observable<WishResponse>;

  deleteWishById(request: FindWishByIdRequest): Observable<WishResponse>;

  getShrineWishCount(request: GetShrineWishCountRequest): Observable<ShrineWishCountResponse>;
}

export interface WishingServiceController {
  createWish(request: CreateWishRequest): Promise<WishResponse> | Observable<WishResponse> | WishResponse;

  findWishById(request: FindWishByIdRequest): Promise<WishResponse> | Observable<WishResponse> | WishResponse;

  findAllWishes(request: FindAllWishesRequest): Promise<WishesResponse> | Observable<WishesResponse> | WishesResponse;

  updateWishById(request: UpdateWishByIdRequest): Promise<WishResponse> | Observable<WishResponse> | WishResponse;

  deleteWishById(request: FindWishByIdRequest): Promise<WishResponse> | Observable<WishResponse> | WishResponse;

  getShrineWishCount(
    request: GetShrineWishCountRequest,
  ): Promise<ShrineWishCountResponse> | Observable<ShrineWishCountResponse> | ShrineWishCountResponse;
}

export function WishingServiceControllerMethods() {
  return function (constructor: Function) {
    const grpcMethods: string[] = [
      "createWish",
      "findWishById",
      "findAllWishes",
      "updateWishById",
      "deleteWishById",
      "getShrineWishCount",
    ];
    for (const method of grpcMethods) {
      const descriptor: any = Reflect.getOwnPropertyDescriptor(constructor.prototype, method);
      GrpcMethod("WishingService", method)(constructor.prototype[method], method, descriptor);
    }
    const grpcStreamMethods: string[] = [];
    for (const method of grpcStreamMethods) {
      const descriptor: any = Reflect.getOwnPropertyDescriptor(constructor.prototype, method);
      GrpcStreamMethod("WishingService", method)(constructor.prototype[method], method, descriptor);
    }
  };
}

export const WISHING_SERVICE_NAME = "WishingService";
