apiVersion: apps/v1
kind: Deployment
metadata:
  name: location-service
  namespace: microservices
  labels:
    app: location-service
spec:
  replicas: 3
  selector:
    matchLabels:
      app: location-service
  template:
    metadata:
      labels:
        app: location-service
    spec:
      containers:
        - name: location-service
          image: location-service:latest
          imagePullPolicy: Never # For local Docker Desktop
          ports:
            - containerPort: 5006
          env:
            - name: NODE_ENV
              valueFrom:
                configMapKeyRef:
                  name: microservices-config
                  key: NODE_ENV
            - name: LOCATION_GRPC_PORT
              valueFrom:
                configMapKeyRef:
                  name: microservices-config
                  key: LOCATION_GRPC_PORT
          resources:
            requests:
              memory: '256Mi'
              cpu: '250m'
            limits:
              memory: '512Mi'
              cpu: '500m'
---
apiVersion: v1
kind: Service
metadata:
  name: location-service
  namespace: microservices
spec:
  selector:
    app: location-service
  ports:
    - port: 5006
      targetPort: 5006
  type: ClusterIP

---
# Horizontal Pod Autoscaler for location-service
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: location-service-hpa
  namespace: microservices
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: location-service
  minReplicas: 1
  maxReplicas: 10
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 50
